services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    container_name: postgres_db

  fastapi-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 80:8000
    restart: unless-stopped
    env_file: 
      - ../.env
    depends_on:
      - db
    # command: ["python", "-m", "app.main"]
    container_name: fastapi-app01
      
volumes:
  postgres_data: